### ISSUE TITLE
Rasperry Pi example does not work as is

### ISSUE THREAD

**Issue by Flauer741** [meta-flutter/meta-flutter#1]
First: Thanks for the great effort to bring flutter to embedded devices.

I tried to build & run the example for the raspberry-pi 4 given in the README and ran into some issues:

First I did not know how to actually run the flutter-gallery. It would be nice to add this to the readme:

```
flutter-pi /usr/share/flutter-gallery/flutter-assets
```

When running this, flutter-pi was unable to enumerate the DRI devices. The reason was that all kernel modules (expect i2c) were missing. I fixed that in `local.conf` with:

```
IMAGE_INSTALL_append = " kernel-modules"
```

After that flutter-pi could not find `/usr/share/flutter/icudtl.dat`. I fixed that issue with:

```
IMAGE_INSTALL_append = " flutter-engine"
```

The issue then was that flutter-engine was in release-mode while the gallery was in debug. I could not figure out how to put the gallery into release, but I was able to change the engine with

```
PACKAGECONFIG_pn-flutter-engine = "disable-desktop-embeddings embedder-for-target fontconfig full-dart-sd
k mode-debug"
```

I also stumbled across https://github.com/jwinarske/meta-flutter/issues/33#issuecomment-890282742 and applied the changes provided there to the flutter-gallery recipe, but I am not sure if that was actually needed.

(Moved here from old repo https://github.com/jwinarske/meta-flutter/issues/43)

**Comment by jwinarske** [comment]
Thanks for reporting this.  I think the delta is that all my notes are around Wayland Yocto builds, and I don't do much smoke testing on flutter-pi (DRM).   I'll make a point of updating the readme and adding changes for a stripped RPI4 DRM build.

**Comment by jwinarske** [comment]
First successful honister rpi4-64 CI job is publishing artifacts here: https://github.com/meta-flutter/meta-flutter/actions/runs/1419261815

Found issue when building `honister` for debug image: https://github.com/meta-flutter/meta-flutter/issues/4

The build artifacts are runtime=release.  I haven't smoke tested the image yet.  Feel free to report back if you get to it first.

Planning to add alternate recipe `flutter-pi-service` which will add drm rules and system service.  Then the default CI job will generate a `boot to flutter` image.

**Comment by jwinarske** [comment]
It boots and runs gallery with minor change:
```
cp /usr/share/homescreen/bundle/libapp.so /usr/share/homescreen/bundle/flutter_assets/app.so
flutter-pi --release /usr/share/homescreen/bundle/flutter_assets
```
I'll address this with upcoming recipe addition - patch to use unified layout.

As a side bonus I have the raspberrypi4-64 vulkan driver building and running in the same image.

**Comment by jwinarske** [comment]
* Updated readme in main to reflect latest state.
* Create honister branch and CI job
* CI artifact sdcard image runs Gallery release build on target.
* flutter-pi runtime dependency `flutter-engine` was missing.  The issue was masked as I always had flutter-pi in addition to another embeder.
* `IMAGE_INSTALL` does not work when building `core-image-minimal`, only `CORE_IMAGE_EXTRA_INSTALL` does.
* Vulkan Driver is functional.  Test using vulkaninfo.  Patches sent upstream.
