### ISSUE TITLE
Remove path patches for flutter-pi

### ISSUE THREAD

**Issue by ardera** [meta-flutter/meta-flutter#209]
I just merged https://github.com/ardera/flutter-pi/pull/290, you can now enable the meta-flutter filesystem layout in flutter-pi by configuring with `cmake ... -DFILESYSTEM_LAYOUT=meta-flutter ...`.

So https://github.com/meta-flutter/meta-flutter/blob/kirkstone/recipes-graphics/flutter-pi/files/0001-path-updates.patch is no longer necessary (and will probably also fail to apply now)

**Comment by jwinarske** [comment]
@ardera That's great, thanks.  I'll take a look in a few days.

**Comment by ardera** [comment]
Closing because #210 #211 #212 were merged
