### ISSUE TITLE
Documentation Issue: default flutter version

### ISSUE THREAD

**Issue by ardera** [meta-flutter/meta-flutter#223]
The readme states that the flutter engine commit / SDK tag defaults to master, if not specified in the `local.conf`: https://github.com/meta-flutter/meta-flutter/blob/4e8950a3a6aa203723436b8718a29040a0c537f2/README.md?plain=1#L36

However in the `flutter-version.inc`, `FLUTTER_SDK_TAG` actually defaults to 3.3.7:
https://github.com/meta-flutter/meta-flutter/blob/4e8950a3a6aa203723436b8718a29040a0c537f2/conf/include/flutter-version.inc#L1

EDIT: Also, seems like `FLUTTER_SDK_TAG=AUTOINC` will make meta-flutter use the latest stable channel, not latest master (as specified in the readme):
https://github.com/meta-flutter/meta-flutter/blob/4e8950a3a6aa203723436b8718a29040a0c537f2/conf/include/flutter-version.inc#L23-L24

**Comment by jwinarske** [comment]
I'll update the doc.  Thanks

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/commit/24168d615494fb1e7191f8b77f550d77c3d1faa3
