### ISSUE TITLE
ERROR: flutter-engine-git-r0 do_fetch: Bitbake Fetcher

### ISSUE THREAD

**Issue by WolsYang** [meta-flutter/meta-flutter#234]
Is the mirror not work at this moment?
```
$ bitbake flutter-engine

ERROR: flutter-engine-git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'gn://github.com/flutter/engine.git;name=src/flutter')
```

**Comment by jwinarske** [comment]
It's working fine with the CI jobs.  Perhaps a network issue on your end.

What overrides are you using?

**Comment by WolsYang** [comment]
Sorry, what's means about overrides ?

I am work on Yocto Project 4.0 (Kirkstone)
```
$ git clone https://github.com/meta-flutter/meta-flutter.git
# Then
$ bitbake flutter-engine
```

**Comment by jwinarske** [comment]
You are missing quite a few steps.  Are you able to build a core-image-minimal?

**Comment by WolsYang** [comment]
Yes

I already build a 'imx-image-full' which is imx full linux image.

Before include 'flutter-engine', I wish I can make sure this recipe work, that why I only $ bitbake flutter-engine.

Should I just add it to my linux recipe and try again ?

**Comment by jwinarske** [comment]
Try `bitbake flutter-engine-runtimerelease`.  Unless you're using the `jw/remove_bbclass` branch.

**Comment by jwinarske** [comment]
Take a look at the CI jobs under the .github folder for reference usage.
