### ISSUE TITLE
History rewrite?

### ISSUE THREAD

**Issue by witekio-kwe** [meta-flutter/meta-flutter#260]
Currently our manifest points to commit 78fa318660b68179adaf22c880b9501fe0ac956e - which apparently isn’t part of any branch anymore - was the history rewritten in this repo? and if so, why?

**Comment by jwinarske** [comment]
I think it's from the fact I do a squash and merge for PRs.  Which would account for the implicit force push, and orphaned commit.  No force pushes happen on primary branches.  So sticking to a primary branch is the way to go.
