### ISSUE TITLE
[3.7.x] Flutter App builds - generating verbose output

### ISSUE THREAD

**Issue by edrose-tewke** [meta-flutter/meta-flutter#273]
When including `meta-flutter` in a Yocto project, the console output is flooded with output stating the git commits of various flutter packages. This is due to lots of `bbnote` calls being made within the recipe files.

Is it possible to remove those calls? They hide useful warning messages from the OpenEmbedded build system and I'm not seeing the value that is has to developers.

**Comment by edrose-tewke** [comment]
In fact it seems the main one is from `conf/include/flutter-version.inc` which is included by multiple recipes, and therefore the git commit is printed out many many times.

**Comment by FranzForstmayr** [comment]
@edrose-tewke 
I triggered the same when building `flutter-test-video-player` which is included in `packagegroup-flutter-test-apps.bb`. Is this recipe built in your case?

**Comment by jwinarske** [comment]
@FranzForstmayr what branch and what commit are you working with?

**Comment by jwinarske** [comment]
As it was fixed some time back

**Comment by FranzForstmayr** [comment]
Latest commit from here:
8ea32557380be576c1477bebad8729d62018cfda

Error was something about `utf-8` issues, but maybe this an different issue.

**Comment by jwinarske** [comment]
Closing issue due to lack of response from issue creator.
