### ISSUE TITLE
Question Regarding "linux" Directory Note

### ISSUE THREAD

**Issue by lapumb-spindance** [meta-flutter/meta-flutter#340]
It is stated in [flutter-app.inc](https://github.com/meta-flutter/meta-flutter/blob/d92cd0784a01ac417b6f592f3ff6cacda8fe4a5f/classes/flutter-app.inc#L5-L7) that the `flutter-app` class _assumes_ there is no "linux" directory, yet the [Flutter Gallery](https://github.com/flutter/gallery/tree/6a8d738c94d0710e229d726729c09fdb5ccaf7ed) example ([flutter-gallery_git.bb](https://github.com/meta-flutter/meta-flutter/blob/kirkstone/recipes-graphics/flutter-apps/flutter-gallery_git.bb)) contains a "linux" directory. Is this a stale note? I created a Flutter application (which has a "linux" directory) and have observed no issues on my target device.

**Comment by jwinarske** [comment]
When federated plugins are present, it will build the Linux platform by default.  This a tooling default when Linux is enabled.  It uses the native platform channel implementation from the embedder.  So we ignore the native code in the plug-in projects, and only use what's available in the embedder.

I can support firebase using this method, among others.

**Comment by jwinarske** [comment]
Updated comment; by removal
https://github.com/meta-flutter/meta-flutter/pull/353
