### ISSUE TITLE
Change branch in recipe from "master" to "main"

### ISSUE THREAD

**Issue by kckemper** [meta-flutter/meta-flutter#352]
In flutter-gallery_git.bb line 16 should be:
`
SRC_URI = "git://github.com/flutter/gallery.git;lfs=0;branch=main;protocol=https;destsuffix=git"
`
(change "branch=master" to "branch=main")

https://github.com/meta-flutter/meta-flutter/blob/19f8ee7125c5621a9ac6eb3d236c573318f7e0ec/recipes-graphics/flutter-apps/flutter-gallery_git.bb#L16C62-L16C68

**Comment by jwinarske** [comment]
@kckemper thanks for the catch

**Comment by jwinarske** [comment]
This works.  It pulls commit from March.  Seems they have an alias to main

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/355

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/355
