### ISSUE TITLE
Please check for build errors.

### ISSUE THREAD

**Issue by Teddywonseokyoo** [meta-flutter/meta-flutter#361]
I'm trying to build it with flutter-engine.
The latest #359 has been checked out.

I get an error like the following image:
![error](https://github.com/meta-flutter/meta-flutter/assets/28579160/2204106c-fc78-41b9-be1a-48685c3a42e3)

Please help.

**Comment by DarthLowen** [comment]
You're likely compiling the `kirstone` branch in an older yocto? You could just try removing references to the `debug2` method, or switch to a more recent yocto version (like `kirkstone`)

**Comment by jwinarske** [comment]
@Teddywonseokyoo what yocto release are you working with?

**Comment by Teddywonseokyoo** [comment]
Hi.
I already know that my yocto version is dufell.
However, if meta-flutter is checked out with dunfell, an error like #362 occurs.
Checkeout with d92cd07 and the build was successful. thank you.

**Comment by jwinarske** [comment]
@Teddywonseokyoo okay you are unblocked, great.  After my current CES work I will get dunfell updated.

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/386
