### ISSUE TITLE
'Illegal instruction' error if I run the flutter gallery app on the toradex imx6 board. 

### ISSUE THREAD

**Issue by JesvinJoseph** [meta-flutter/meta-flutter#363]
Hi,

I am trying to run the flutter-gallery app on the tordex board. It was working fine before but with the latest meta-flutter I am getting the 'illegal instruction' error. 

<img width="510" alt="image" src="https://github.com/meta-flutter/meta-flutter/assets/42056590/1fc593df-a8cf-4ff4-aadf-6e8e23d48318">

weston-terminal also works fine. 

Am I missing any configuration?

**Comment by jwinarske** [comment]
Potentially a repro of this: https://github.com/meta-flutter/meta-flutter/issues/204

Two experiments to try:
1. Try building and running with jit_release engine variant.
1. Next try setting APP_AOT_EXTRA in your app recipe to `--no-use-integer-division`

I would do these independent of each other, then together.  So three total attempts.

**Comment by JesvinJoseph** [comment]
@jwinarske Thank you for the quick suggestion. I will try them and will let you know the result.

**Comment by JesvinJoseph** [comment]
Hi @jwinarske ,

I was trying the first option. Below are the changes I made to use the jit_release but I am getting build error. Am I on the correct way?

1. In the flutter-engine.bbappend file I added `PACKAGECONFIG:append = " jit_release"`
2. On my app, I added `FLUTTER_APP_RUNTIME_MODES = "jit_release"`

The build error is 

> The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_compile(d)
     0003:
File: '/home/jesvin/kirkstone/build/../meta-flutter/conf/include/flutter-app.inc', lineno: 225, function: do_compile
     0221:        run_command(d, 'flutter clean', source_root, env)
     0222:
     0223:        if runtime_mode == 'jit_release':
     0224:            cmd = (f'flutter build {flutter_build_args} --local-engine')
 *** 0225:            run_command(cmd, source_root, env)
     0226:        else:
     0227:            cmd = f'flutter build {flutter_build_args}'
     0228:            run_command(d, cmd, source_root, env)
     0229:
Exception: TypeError: run_command() missing 1 required positional argument: 'env'

**Comment by jwinarske** [comment]
@JesvinJoseph I'll take a look, looks like a regression

**Comment by JesvinJoseph** [comment]
@jwinarske ,

Thanks,

Also for the second option, I got error while building with `APP_AOT_EXTRA `. It says there is no argument like `--no-use-integer-division`. But instead I tried with `APP_GEN_SNAPSHOT_FLAGS="--no-use-integer-division"`, then it worked without jit_release.

**Comment by jwinarske** [comment]
@JesvinJoseph that's great.  Thanks for the update.
