### ISSUE TITLE
libstd-rs_%.bbappend caused libstd-rs build fail

### ISSUE THREAD

**Issue by onlyxuyang** [meta-flutter/meta-flutter#370]
libstd-rs_%.bbappend change S to a strange folder in RUSTSRC, and it will caused build fail.

Why we need this bbappend?

**Comment by jwinarske** [comment]
@onlyxuyang the history on that is located here:
https://github.com/meta-rust/meta-rust/issues/266

**Comment by onlyxuyang** [comment]
@jwinarske 
> @onlyxuyang the history on that is located here: [meta-rust/meta-rust#266](https://github.com/meta-rust/meta-rust/issues/266)

Thank you for your information. I use meta-rust [f6a80656953678f17de7d41343107112d99492d9](https://github.com/meta-rust/meta-rust/commit/f6a80656953678f17de7d41343107112d99492d9)  with rust version 1.73.0.

Yes, this bbappend not compatible with latest rust in meta-rust.

And though no libproc_macro-xx.rlib under ${WORKDIR}/recipe-sysroot,  
but libproc_macro2-xx.rlib is under ${WORKDIR}/build/target/release/deps/  and my package is build pass.

Could we verify this bbappend is still necessary or apply it only excepted version?

Thank you

**Comment by jwinarske** [comment]
@onlyxuyang yes that makes sense.  I will make it version specific.  Thanks for filling the issue

**Comment by svarmeddev** [comment]
I have same issue

**Comment by kusstas** [comment]
I have same issue

**Comment by jwinarske** [comment]
I'll push a change in the next couple of days

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/371
