### ISSUE TITLE
failed run_command not added to bitbake logs

### ISSUE THREAD

**Issue by Markus43** [meta-flutter/meta-flutter#476]
run_command in common.inc ( see [here](https://github.com/meta-flutter/meta-flutter/blob/6f431e743a878c738d35383c5cbabda71ba6538f/conf/include/common.inc#L62)) finishes via sys.exit if an eror occurs, e.g in a flutter command. The bitbake error message then shows a location where to expect more details to the occurred error.

The error however is not included in that log file, which was quite confusing to me, until I traced down the issue to this sys.exit call.

Improvement suggestions (I don't know if sys.exit is necessary here):
* either use bb.fatal, which should have the same effect but logs the error
* or call bb.error with the message before calling sys.exit

**Comment by jwinarske** [comment]
It would have logged to the `log.do_compile` file.

For example for `flutter-gallery` (starting from build folder):
```
cat tmp/work/cortexa76-poky-linux/flutter-gallery/2.10.2-r0/temp/log.do_compile
```

You're stating the output is not present in the compile log?
