### ISSUE TITLE
do_archive_pub_cache also copies parent directories 

### ISSUE THREAD

**Issue by jgerdes5** [meta-flutter/meta-flutter#490]
I found a bug while the function 'do_archive_pub_cache' copies the project, where it will also copy the parent directories. This resulted in completely decimating my available hard drive space and finally stopping, because there was no space left. It happens when using bash as a terminal.

The offender is the following line in /conf/include/common.inc:153

`    cp_cmd = \
        'mkdir -p %s/.project | true; ' \
        'cp -r .* %s/.project/ | true; ' \
        % (pub_cache, pub_cache)
`

This will also copy the directories '.' and '..'. The bug is present while using bash or zsh. Other shells I haven't tested.

Here is the log.do_archive_pub_cache file:

<details>
<summary>log.do_archive_pub_cache</summary>
DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['virtual:native:/home/username/poky/meta-flutter/recipes-graphics/flutter-sdk/flutter-sdk_git.bb:do_populate_sysroot', 'virtual:native:/home/username/poky/meta/recipes-extended/pbzip2/pbzip2_1.1.13.bb:do_populate_sysroot']
NOTE: Installed into sysroot: ['flutter-sdk-native', 'pbzip2-native', 'bzip2-native', 'curl-native', 'xz-native', 'unzip-native', 'fontconfig-native', 'perl-native', 'pango-native', 'ca-certificates-native', 'atk-native', 'gtk+3-native', 'libtool-native', 'openssl-native', 'zlib-native', 'gettext-minimal-native', 'expat-native', 'freetype-native', 'util-linux-native', 'make-native', 'gdbm-native', 'fribidi-native', 'libxft-native', 'libx11-native', 'harfbuzz-native', 'cairo-native', 'gobject-introspection-native', 'python3-native', 'glib-2.0-native', 'gettext-native', 'libxcomposite-native', 'libpng-native', 'libjpeg-turbo-native', 'at-spi2-atk-native', 'libxext-native', 'libxi-native', 'libxrandr-native', 'libxrender-native', 'libxcursor-native', 'libxdamage-native', 'libxfixes-native', 'gdk-pixbuf-native', 'texinfo-dummy-native', 'cmake-native', 'ncurses-native', 'libpcre2-native', 'libcap-ng-native', 'util-linux-libuuid-native', 'util-macros-native', 'xtrans-native', 'libxcb-native', 'xorgproto-native', 'icu-native', 'libsm-native', 'pixman-native', 'flex-native', 'libffi-native', 'libnsl2-native', 'libtirpc-native', 'sqlite3-native', 'readline-native', 'libpcre-native', 'at-spi2-core-native', 'dbus-native', 'libxml2-native', 'shared-mime-info-native', 'zstd-native', 'libxdmcp-native', 'libpthread-stubs-native', 'libxau-native', 'xcb-proto-native', 'libice-native', 'm4-native', 'libxtst-native', 'itstool-native', 'gnu-config-native']
NOTE: Skipping as already exists in sysroot: []
DEBUG: sed -e 's:^[^/]*/:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/:g' /home/username/poky/build/tmp/sysroots-components/aarch64/curl-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/fontconfig-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/perl-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/libtool-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/openssl-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/gobject-introspection-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/python3-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/glib-2.0-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/gettext-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/libpng-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/gdk-pixbuf-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/ncurses-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/libpcre2-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/icu-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/libpcre-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/at-spi2-core-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/dbus-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/libxml2-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/itstool-native/fixmepath /home/username/poky/build/tmp/sysroots-components/aarch64/gnu-config-native/fixmepath | xargs sed -i -e 's:FIXMESTAGINGDIRTARGET:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot:g; s:FIXMESTAGINGDIRHOST:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native:g' -e 's:FIXME_PSEUDO_SYSROOT:/home/username/poky/build/tmp/sysroots-components/aarch64/pseudo-native:g' -e 's:FIXME_HOSTTOOLS_DIR:/home/username/poky/build/tmp/hosttools:g' -e 's:FIXME_PKGDATA_DIR:/home/username/poky/build/tmp/pkgdata/raspberrypi4-64:g' -e 's:FIXME_PSEUDO_LOCALSTATEDIR:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pseudo/:g' -e 's:FIXME_LOGFIFO:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/temp/fifo.7618:g'
DEBUG: Python function extend_recipe_sysroot finished
DEBUG: Executing python function do_archive_pub_cache
NOTE: Running [export PUB_CACHE=/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pub_cache; export XDG_CONFIG_HOME=/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0;export PATH=/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin:/home/username/poky/build/tmp/sysroots-uninative/aarch64-linux/usr/bin:/home/username/poky/scripts:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot/usr/bin/crossscripts:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/sbin:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/bin:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/sbin:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/bin:/home/username/poky/bitbake/bin:/home/username/poky/build/tmp/hosttools:;] in /home/username/customapp/
NOTE: Running [export PUB_CACHE=/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pub_cache; export XDG_CONFIG_HOME=/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0;export PATH=/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin:/home/username/poky/build/tmp/sysroots-uninative/aarch64-linux/usr/bin:/home/username/poky/scripts:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot/usr/bin/crossscripts:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/sbin:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/usr/bin:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/sbin:/home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/recipe-sysroot-native/bin:/home/username/poky/bitbake/bin:/home/username/poky/build/tmp/hosttools:;] in /home/username/customapp/
NOTE: Running [flutter config --no-analytics] in /home/username/customapp/
NOTE: Running [flutter config --no-cli-animations] in /home/username/customapp/
NOTE: Running [flutter clean] in /home/username/customapp/
NOTE: Running [flutter pub get] in /home/username/customapp/
NOTE: Running [flutter pub get --offline] in /home/username/customapp/
NOTE: Running [mkdir -p /home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pub_cache/.project | true; cp -r .* /home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pub_cache/.project/ | true; ] in /home/username/customapp/
NOTE: Running [mkdir -p /home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pub_cache/.project | true; cp -r .* /home/username/poky/build/tmp/work/cortexa72-poky-linux/customapp/1.0+git999-r0/pub_cache/.project/ | true; ] in /home/username/customapp/
</details>

System: Macbook Pro (M2) running Ubuntu 22.04.3 LTS ARM64 Version in a VM

**Comment by jwinarske** [comment]
Resolved by https://github.com/meta-flutter/meta-flutter/pull/573
