### ISSUE TITLE
kirkstone/scarthgap parity

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#538]
`kirkstone` needs to be at parity with `scarthgap` for vNext work

**Comment by jwinarske** [comment]
cc @WAKazuyoshiAkiyama

**Comment by WAKazuyoshiAkiyama** [comment]
What is `vNext`?

**Comment by jwinarske** [comment]
@WAKazuyoshiAkiyama "version Next".  I'm our case the project after 24mm.

**Comment by jwinarske** [comment]
moved out to end of October due to internal priority changes

**Comment by jwinarske** [comment]
resolved with https://github.com/meta-flutter/meta-flutter/pull/588
