### ISSUE TITLE
Which layer provides python3-pycurl-native? Flutter app build depends on this

### ISSUE THREAD

**Issue by JesvinJoseph** [meta-flutter/meta-flutter#550]
I am getting the below error while building flutter gallery

>ERROR: Nothing PROVIDES 'python3-pycurl-native' (but meta-flutter/meta-flutter-apps/recipes-graphics/flutter-apps/first-party/flutter-gallery_2.10.2.bb DEPENDS on or otherwise requires it). Close matches:
  python3-ply-native
  python3-py-native
  python3-pycairo-native
ERROR: Required build target 'flutter-gallery' has no buildable providers.
Missing or unbuildable dependency chain was: ['flutter-gallery', 'python3-pycurl-native']

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/551

meta-python is located under meta-openembedded

**Comment by JesvinJoseph** [comment]
@jwinarske ,

Thank you for the response. Now getting the error

> No module named 'pycurl'

**Comment by jwinarske** [comment]
@JesvinJoseph The short term workaround is to install `pycurl` on the build host; unless you're fixed on a container that doesn't have it installed like the TI guy.
