### ISSUE TITLE
flutter-sdk recipe - add `do_archive_pub_cache task`

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#556]
Flutter SDK needs a `do_archive_cache_task`.

This would walk the SDK tree archiving all pubspec.lock files; pre-populating the $DL_DIR/pub_cache folder.

This alleviates `n` number of application recipes downloading the same packages at once.

Another approach would be to skip the file if it's already locked.

**Comment by JesvinJoseph** [comment]
> ModuleNotFoundError: No module named 'yaml'

**Comment by jwinarske** [comment]
@JesvinJoseph
> ModuleNotFoundError: No module named 'yaml'

How is this related to adding a new task to the flutter-sdk recipe?

**Comment by JesvinJoseph** [comment]
> @JesvinJoseph
> 
> > ModuleNotFoundError: No module named 'yaml'
> 
> How is this related to adding a new task to the flutter-sdk recipe?

Not with this task. I mean after merging the branches, I can see this error while building the app. I will post it in another topic
