### ISSUE TITLE
PUBSPEC_IGNORE_LOCKFILE is undocumented

### ISSUE THREAD

**Issue by pogojotz** [meta-flutter/meta-flutter#563]
`PUBSPEC_IGNORE_LOCKFILE` used to be in the README.md, was functionally removed from code and documentation and later reintroduced into the code, but without documentation.

Is this on purpose and only supposed to be an internal switch for the example flutter-apps or here to stay as public API? Because the `--enforce-lockfile` switch breaks my workflow and I could live with the `PUBSPEC_IGNORE_LOCKFILE` functionality as a workaround.

**Comment by jwinarske** [comment]
At this point I am finding no scenarios why one should preserve the lock file.
The lock file is relative to the SDK version.  If something is checked in with a different SDK than what you are trying to build with, it will likely fail.  Setting `PUBSPEC_IGNORE_LOCKFILE` will delete the lock file if present.  Most if not all of the first party flutter apps do not have the pubspec.lock file checked in.

Documentation added back via https://github.com/meta-flutter/meta-flutter/pull/564
