### ISSUE TITLE
OpenEmbedded Layer index pointing to old repository

### ISSUE THREAD

**Issue by esben** [meta-flutter/meta-flutter#58]
The [meta-flutter entry](https://layers.openembedded.org/layerindex/branch/master/layer/meta-flutter/) needs to be updated to refer to the new repository URL.

**Comment by jwinarske** [comment]
Agreed

**Comment by jwinarske** [comment]
Trying to login my account got locked.  No idea who the owner/contact is.

**Comment by esben** [comment]
The site supports password reset. https://layers.openembedded.org/accounts/login/

**Comment by bernardcraddock** [comment]
maybe someone here can advise https://www.openembedded.org/wiki/Mailing_lists

**Comment by jwinarske** [comment]
Finally updated!
