### ISSUE TITLE
Host contamination with flutter, dart, vpython and depot_tools

### ISSUE THREAD

**Issue by StaticRocket** [meta-flutter/meta-flutter#612]
Each of the above listed tools attempt to store temporary data, configs, and build cache in directories outside of bitbake's control. These tend to be:

- `$HOME`
- `$XDG_CONFIG_HOME`
- `$XDG_CACHE_HOME`
- `$XDG_DATA_HOME`

This can negatively affect the reproducibility of build artifacts by allowing individual recipes to adjust global caches and configs.

To catch these accesses I use an immutable build container where the user's home directory is also read only.

This is the only layer in my testing that has recipes that attempt to interact with the users home directory.

**Comment by jwinarske** [comment]
Can you share more info on an immutable container?  I would like to switch to this in CI.  Then there is no need for more of these issues in the future.

thanks!

**Comment by StaticRocket** [comment]
Yeah, I use the crops container as a starting point. Here's my launch command:

```bash
podman run --rm -it \
	--read-only \
	--pull newer \
	--userns keep-id \
	--network host \
	-v "$HOME/.ssh":"/home/yoctouser/.ssh":ro \
	-v /yocto:/yocto \
	--log-driver=none \
	-u "$(id -u)":"$(id -g)" \
	--entrypoint dumb-init \
	ghcr.io/crops/poky:ubuntu-22.04 \
	bash -c "cd $PWD; exec bash -l"
```

The `/yocto` directory is just a global sstate cache. The ssh volume mount is just for some internal stuff. It can be ignored for general builds.

https://man.archlinux.org/man/podman-run.1#Running_container_in_read-only_mode

**Comment by jwinarske** [comment]
@StaticRocket cool thanks.  I’ll get this implemented before I head out of town on Thursday

**Comment by jwinarske** [comment]
resolved with https://github.com/meta-flutter/meta-flutter/pull/611
