### ISSUE TITLE
Set default tag

### ISSUE THREAD

**Issue by rzr** [meta-flutter/meta-flutter#84]
This layer wont work out of the box without setting the sdk tag currently:

FLUTTER_SDK_TAG = "2.10.2"

Would it be possible to just set AUTOREV in CI recipes and default to supported tag ?

Relate-to: https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/pipelines/2330

https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/merge_requests/4

**Comment by jwinarske** [comment]
@rzr The LTS support I just merged into Dunfell has default set.  This will go into Honister branch soon.

**Comment by jwinarske** [comment]
Default FLUTTER_SDK_TAG is set to 2.10.3 in latest honister commit.

**Comment by rzr** [comment]
Thanks would it be also possible create a branch for next LTS kirkstone (expected this coming april https://wiki.yoctoproject.org/wiki/Releases# )
