### ISSUE TITLE
[STM32MP15] Problems deploying Flutter App on STM32MP157C-DK2

### ISSUE THREAD

**Issue by ck-schmidi** [meta-flutter/meta-flutter#87]
Hi, I'm trying to get a running setup for the _STM32MP157C-DK2_ board. 

I tried a prebuild image from 2 days ago (<https://github.com/meta-flutter/meta-flutter/actions/runs/1977985359>)

Successfully flashed the image on the hardware with:

`STM32_Programmer_CLI -c port=USB1 -w flashlayout_st-image-core/trusted/FlashLayout_sdcard_stm32mp157c-dk2-trusted.tsv`

I configured a proper custom device for using it with flutter tools and tried to deploy the application to board:

`flutter install -d stm32mp1_disco` (which works fine)

But when I try to run the application with `flutter run -d stm32mp1_disco` I get the following error:

```
...
[INFO:app.cc(147)] -App::App
[INFO:egl_window.cc(361)] ** handle_shell_configure_callback **
[ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[ERROR:flutter/runtime/dart_isolate.cc(141)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
```
Is it something (maybe a mismatch of versions) with my local Flutter version (I locally use the `master` branch)? 

Output `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.13.0-0.0.pre.103, on Ubuntu 20.04.3 LTS 5.13.0-35-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] VS Code
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```

Thank you in advance!

**Comment by jwinarske** [comment]
@ck-schmidi 
That build is using the latest flutter channel stable: `FLUTTER_SDK_TAG = "2.10.3"`

What should resolve your scenario:
```
flutter channel stable
flutter upgrade
``
